In [ ]:
import numpy as np

#**NumPy Array**

In [ ]:
# 1.How to create an empty and a full NumPy array?
print('\033[1m' + "1.How to create an empty and a full NumPy array?\n" + '\033[0m')

emptyArray = np.empty((2, 4))
print("Empty Array: \n", emptyArray, "\n")
fullArray = np.full((2, 4), 29)
print("Full Array: \n", fullArray)

1.How to create an empty and a full NumPy array?

Empty Array: 
 [[1.43e-322 1.43e-322 1.43e-322 1.43e-322]
 [1.43e-322 1.43e-322 1.43e-322 1.43e-322]] 

Full Array: 
 [[29 29 29 29]
 [29 29 29 29]]


In [ ]:
# 2.Create a Numpy array filled with all zeros
print('\033[1m' + "2.Create a Numpy array filled with all zeros\n" + '\033[0m')

zerosArray = np.zeros((2, 3))
print("Array of Zeros: \n", zerosArray)

2.Create a Numpy array filled with all zeros

Array of Zeros: 
 [[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# 3.Create a Numpy array filled with all ones
print('\033[1m' + "3.Create a Numpy array filled with all ones\n" + '\033[0m')

onesArray = np.ones((2, 3))
print("Array of Ones: \n", onesArray)

3.Create a Numpy array filled with all ones

Array of Ones: 
 [[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# 4.Check whether a Numpy array contains a specified row
print('\033[1m' + "4.Check whether a Numpy array contains a specified row\n" + '\033[0m')

array = np.array([[1, 2, 3], 
                  [4, 5, 6]])
row = [4, 5, 6]
if(row in array.tolist()):
    print("Row: ", row, "\nEstá contido no array: \n", array)

4.Check whether a Numpy array contains a specified row

Row:  [4, 5, 6] 
Está contido no array: 
 [[1 2 3]
 [4 5 6]]


In [ ]:
# 5.How to Remove rows in Numpy array that contains non-numeric values?
print('\033[1m' + "5.How to Remove rows in Numpy array that contains non-numeric values?\n" + '\033[0m')

arr = np.array([[1, 2, 3], 
                [4, 5, np.nan]])
arrayWithoutNaN = arr[~np.isnan(arr).any(axis=1)]
print("Array: \n", arr, "\nArray sem linhas com valores NaN: \n", arrayWithoutNaN)

5.How to Remove rows in Numpy array that contains non-numeric values?

Array: 
 [[ 1.  2.  3.]
 [ 4.  5. nan]] 
Array sem linhas com valores NaN: 
 [[1. 2. 3.]]


In [ ]:
# 6.Remove single-dimensional entries from the shape of an array
print('\033[1m' + "6.Remove single-dimensional entries from the shape of an array\n" + '\033[0m')

array = np.array([[[1, 2, 3]]])
print("Array: \n", array, "\nArray após remoção de eixos com tamanho 1: \n", array.squeeze())

6.Remove single-dimensional entries from the shape of an array

Array: 
 [[[1 2 3]]] 
Array após remoção de eixos com tamanho 1: 
 [1 2 3]


In [ ]:
# 7.Find the number of occurrences of a sequence in a NumPy array
print('\033[1m' + "7.Find the number of occurrences of a sequence in a NumPy array\n" + '\033[0m')

array = np.array([[1, 2, 3], 
                  [4, 5, 6]])
sequence = '4, 5'
print("Array: \n", array, "\nO array possui: ", repr(array).count(sequence), " sequências de (" + sequence + ")")

7.Find the number of occurrences of a sequence in a NumPy array

Array: 
 [[1 2 3]
 [4 5 6]] 
O array possui:  1  sequências de (4, 5)


In [ ]:
# 8.Find the most frequent value in a NumPy array
print('\033[1m' + "8.Find the most frequent value in a NumPy array\n" + '\033[0m')

array = np.array([[1, 8, 2], 
                  [2, 8, 8]])
#print(array.flat.copy())
print("Elemento mais frequente do array: ", np.bincount(array.flat).argmax())

8.Find the most frequent value in a NumPy array

Elemento mais frequente do array:  8


In [ ]:
# 9.Combining a one and a two-dimensional NumPy Array
print('\033[1m' + "9.Combining a one and a two-dimensional NumPy Array\n" + '\033[0m')

arrayTwoDim = np.array([[1, 8, 2], 
                        [2, 8, 8]])

arrayOneDim = np.array([1, 2, 3])
print("Array com uma dimensão: \n", arrayOneDim)
print("Array com duas dimensão: \n", arrayTwoDim)
print()
for i, j in np.nditer([arrayOneDim, arrayTwoDim]):
    print(i, "|", j)

9.Combining a one and a two-dimensional NumPy Array

Array com uma dimensão: 
 [1 2 3]
Array com duas dimensão: 
 [[1 8 2]
 [2 8 8]]

1 | 1
2 | 8
3 | 2
1 | 2
2 | 8
3 | 8


In [ ]:
# 10.How to build an array of all combinations of two NumPy arrays?
print('\033[1m' + "10.How to build an array of all combinations of two NumPy arrays?\n" + '\033[0m')

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5])

print("Array 1: \n", array1)
print("Array 2: \n", array2)
combinations = np.array(np.meshgrid(array1, array2)).T.reshape(-1, 2)
print("\nCombinações: \n", combinations)

10.How to build an array of all combinations of two NumPy arrays?

Array 1: 
 [1 2 3]
Array 2: 
 [4 5]

Combinações: 
 [[1 4]
 [1 5]
 [2 4]
 [2 5]
 [3 4]
 [3 5]]


In [ ]:
# 11.How to add a border around a NumPy array?
print('\033[1m' + "11.How to add a border around a NumPy array?\n" + '\033[0m')

array = np.arange(1, 7).reshape(2, 3)

print("Array: \n", array, "\n\nArray com padding: \n", np.pad(array, 2, constant_values=0))

11.How to add a border around a NumPy array?

Array: 
 [[1 2 3]
 [4 5 6]] 

Array com padding: 
 [[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 1 2 3 0 0]
 [0 0 4 5 6 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [ ]:
def isEqual(array1, array2):
    if((array1 == array2).all()):
        print("Os dois arrays são iguais")
    else:
        print("Os dois arrays não são iguais")

# 12.How to compare two NumPy arrays?
print('\033[1m' + "12.How to compare two NumPy arrays?\n" + '\033[0m')

array1 = np.arange(1, 7).reshape(2, 3)
array2 = np.arange(1, 7).reshape(2, 3)

print("Array 1: \n", array1)
print("Array 2: \n", array2)
isEqual(array1, array2)
print()

array2[0][0] = 5
print("Array 1: \n", array1)
print("Array 2: \n", array2)
isEqual(array1, array2)

12.How to compare two NumPy arrays?

Array 1: 
 [[1 2 3]
 [4 5 6]]
Array 2: 
 [[1 2 3]
 [4 5 6]]
Os dois arrays são iguais

Array 1: 
 [[1 2 3]
 [4 5 6]]
Array 2: 
 [[5 2 3]
 [4 5 6]]
Os dois arrays não são iguais


In [ ]:
# 13.How to check whether specified values are present in NumPy array?
print('\033[1m' + "13.How to check whether specified values are present in NumPy array?\n" + '\033[0m')

array = np.arange(1, 7).reshape(2, 3)
value = 6

if(value in array):
    print(f"O valor \"{value}\" está no array: \n{array}")
else:
    print(f"O valor \"{value}\" não está no array: \n{array}")

13.How to check whether specified values are present in NumPy array?

O valor "6" está no array: 
[[1 2 3]
 [4 5 6]]


In [ ]:
# 14.How to get all 2D diagonals of a 3D NumPy array?
print('\033[1m' + "14.How to get all 2D diagonals of a 3D NumPy array?\n" + '\033[0m')

array = np.arange(3 * 2 * 2).reshape(3, 2, 2)
print("3D array: \n", array)
print("\n2D diagonals array: \n", np.diagonal(array, axis1 = 1, axis2 = 2))

14.How to get all 2D diagonals of a 3D NumPy array?

3D array: 
 [[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]

2D diagonals array: 
 [[ 0  3]
 [ 4  7]
 [ 8 11]]


In [ ]:
# 15.Flatten a Matrix in Python using NumPy
print('\033[1m' + "15.Flatten a Matrix in Python using NumPy\n" + '\033[0m')

array = np.arange(1, 7).reshape(2, 3)

print("Matrix: \n", array, "\nFlatten Matrix: \n", array.flatten())

15.Flatten a Matrix in Python using NumPy

Matrix: 
 [[1 2 3]
 [4 5 6]] 
Flatten Matrix: 
 [1 2 3 4 5 6]


In [ ]:
# 16.Flatten a 2d numpy array into 1d array
print('\033[1m' + "16.Flatten a 2d numpy array into 1d array\n" + '\033[0m')

array = np.arange(1, 7).reshape(2, 3)

print("2d numpy array: \n", array, "\nFlatten 2d numpy array: \n", array.flatten())

16.Flatten a 2d numpy array into 1d array

2d numpy array: 
 [[1 2 3]
 [4 5 6]] 
Flatten 2d numpy array: 
 [1 2 3 4 5 6]


In [ ]:
# 17.Move axes of an array to new positions
print('\033[1m' + "17.Move axes of an array to new positions\n" + '\033[0m')

array = np.arange(1, 7).reshape(2, 3)

print("Array: \n", array, "\nArray with moved axes: \n", np.moveaxis(array, 0, -1))

17.Move axes of an array to new positions

Array: 
 [[1 2 3]
 [4 5 6]] 
Array with moved axes: 
 [[1 4]
 [2 5]
 [3 6]]


In [ ]:
# 18.Interchange two axes of an array
print('\033[1m' + "18.Interchange two axes of an array\n" + '\033[0m')

array = np.arange(1, 7).reshape(2, 3)

print("Array: \n", array, "\nArray with moved axes: \n", np.swapaxes(array, 0, 1))

18.Interchange two axes of an array

Array: 
 [[1 2 3]
 [4 5 6]] 
Array with moved axes: 
 [[1 4]
 [2 5]
 [3 6]]


In [ ]:
# 19.NumPy – Fibonacci Series using Binet Formula
print('\033[1m' + "19.NumPy – Fibonacci Series using Binet Formula\n" + '\033[0m')

array = np.arange(1, 15) 

alpha = (1 + np.sqrt(5)) / 2

beta = (1 - np.sqrt(5)) / 2

#np.rint serve para arredondar os elementos do array

fn = np.rint((alpha ** array - beta ** array) / np.sqrt(5)) 

print(f"Os primeiros {len(array)} números da série de Fibonacci {fn}")

19.NumPy – Fibonacci Series using Binet Formula

Os primeiros 14 números da série de Fibonacci [  1.   1.   2.   3.   5.   8.  13.  21.  34.  55.  89. 144. 233. 377.]


In [ ]:
# 20.Counts the number of non-zero values in the array
print('\033[1m' + "20.Counts the number of non-zero values in the array\n" + '\033[0m')

array = np.arange(6).reshape(2, 3)

print("Array: \n", array, "\nQuantidade de valores diferentes de 0: \n", np.count_nonzero(array))

20.Counts the number of non-zero values in the array

Array: 
 [[0 1 2]
 [3 4 5]] 
Quantidade de valores diferentes de 0: 
 5


In [ ]:
# 21.Count the number of elements along a given axis
print('\033[1m' + "21.Count the number of elements along a given axis\n" + '\033[0m')

array = np.arange(6).reshape(2, 3)

print("Array: \n", array, "\nQuantidade de elementos no eixo x(quantidade de linhas): \n", np.size(array, 0))

21.Count the number of elements along a given axis

Array: 
 [[0 1 2]
 [3 4 5]] 
Quantidade de elementos no eixo x(quantidade de linhas): 
 2


In [ ]:
# 22.Trim the leading and/or trailing zeros from a 1-D array
print('\033[1m' + "22.Trim the leading and/or trailing zeros from a 1-D array\n" + '\033[0m')

array = np.arange(6)
array = np.append(array, 0)

print("Array: \n", array, "\nArray após remoção dos zeros: \n", np.trim_zeros(array))

22.Trim the leading and/or trailing zeros from a 1-D array

Array: 
 [0 1 2 3 4 5 0] 
Array após remoção dos zeros: 
 [1 2 3 4 5]


In [ ]:
# 23.Change data type of given numpy array
print('\033[1m' + "23.Change data type of given numpy array\n" + '\033[0m')

array = np.arange(6)
arrayFloat = array.astype('float64')
print("Array: \n", array, "\nArray de floats: \n", arrayFloat)

23.Change data type of given numpy array

Array: 
 [0 1 2 3 4 5] 
Array de floats: 
 [0. 1. 2. 3. 4. 5.]


In [ ]:
# 24.Reverse a numpy array
print('\033[1m' + "24.Reverse a numpy array\n" + '\033[0m')

array = np.arange(6)
arrayFliped = np.flip(array)

print("Array: \n", array, "\nArray reverso: \n", arrayFliped)

24.Reverse a numpy array

Array: 
 [0 1 2 3 4 5] 
Array reverso: 
 [5 4 3 2 1 0]


In [ ]:
# 25.How to make a NumPy array read-only?
print('\033[1m' + "25.How to make a NumPy array read-only?\n" + '\033[0m')

array = np.arange(6)
array.setflags(write=False)

array[0] = 10

25.How to make a NumPy array read-only?



ValueError: ignored

#**Questions on NumPy Matrix**

In [ ]:
# 1.Get the maximum value from given matrix
print('\033[1m' + "1.Get the maximum value from given matrix\n" + '\033[0m')

matrix = np.matrix(np.arange(6).reshape(2, 3))

print("Matrix: \n", matrix, "\nMaximum value: \n", matrix.max())

1.Get the maximum value from given matrix

Matrix: 
 [[0 1 2]
 [3 4 5]] 
Maximum value: 
 5


In [ ]:
# 2.Get the minimum value from given matrix
print('\033[1m' + "2.Get the minimum value from given matrix\n" + '\033[0m')

matrix = np.matrix(np.arange(6).reshape(2, 3))

print("Matrix: \n", matrix, "\nMinimum value: \n", matrix.min())

2.Get the minimum value from given matrix

Matrix: 
 [[0 1 2]
 [3 4 5]] 
Minimum value: 
 0


In [ ]:
# 3.Find the number of rows and columns of a given matrix using NumPy
print('\033[1m' + "3.Find the number of rows and columns of a given matrix using NumPy\n" + '\033[0m')

matrix = np.matrix(np.arange(6).reshape(2, 3))

print("Matrix: \n", matrix, "\nNumber of rows and columns: \n", matrix.shape)

3.Find the number of rows and columns of a given matrix using NumPy

Matrix: 
 [[0 1 2]
 [3 4 5]] 
Number of rows and columns: 
 (2, 3)


In [ ]:
# 4.Select the elements from a given matrix
print('\033[1m' + "4.Select the elements from a given matrix\n" + '\033[0m')

matrix = np.matrix(np.arange(6).reshape(2, 3))

print("Matrix: \n", matrix, "\nSelected elements: \n", np.choose([1, 0, 1], matrix))

4.Select the elements from a given matrix

Matrix: 
 [[0 1 2]
 [3 4 5]] 
Selected elements: 
 [[3 1 5]]


In [ ]:
# 5.Find the sum of values in a matrix
print('\033[1m' + "5.Find the sum of values in a matrix\n" + '\033[0m')

matrix = np.matrix(np.arange(6).reshape(2, 3))

print("Matrix: \n", matrix, "\nSum of values: \n", matrix.sum())

5.Find the sum of values in a matrix

Matrix: 
 [[0 1 2]
 [3 4 5]] 
Sum of values: 
 15


In [ ]:
# 6.Calculate the sum of the diagonal elements of a NumPy array
print('\033[1m' + "6.Calculate the sum of the diagonal elements of a NumPy array\n" + '\033[0m')

matrix = np.matrix(np.arange(9).reshape(3, 3))

print("Matrix: \n", matrix, "\nSum of the diagonal elements: \n", np.trace(matrix))

6.Calculate the sum of the diagonal elements of a NumPy array

Matrix: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]] 
Sum of the diagonal elements: 
 12


In [ ]:
# 7.Adding and Subtracting Matrices in Python
print('\033[1m' + "7.Adding and Subtracting Matrices in Python\n" + '\033[0m')

matrix1 = np.matrix(np.arange(9).reshape(3, 3))
matrix2 = np.matrix(np.ones((3, 3)).astype('int32'))

print("Matrix 1: \n", matrix1)
print("Matrix 2: \n", matrix2)
print("\nAdding: \n", matrix1 + matrix2)
print("\nSubtracting: \n", matrix1 - matrix2)

7.Adding and Subtracting Matrices in Python

Matrix 1: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Matrix 2: 
 [[1 1 1]
 [1 1 1]
 [1 1 1]]

Adding: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Subtracting: 
 [[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]


In [ ]:
# 8.Ways to add row/columns in numpy array
print('\033[1m' + "8.Ways to add row/columns in numpy array\n" + '\033[0m')

matrix = np.matrix(np.arange(9).reshape(3, 3))

row = np.array([1, 2, 3])
col = np.array([[1], [2], [3]])

print("Matrix: \n", matrix)
print("row: \n", row)
print("col: \n", col)
print("\nMatrix with added row: \n", np.r_[matrix, [row]])
print("\nMatrix with added col: \n", np.c_[matrix, col])

8.Ways to add row/columns in numpy array

Matrix: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
row: 
 [1 2 3]
col: 
 [[1]
 [2]
 [3]]

Matrix with added row: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]
 [1 2 3]]

Matrix with added col: 
 [[0 1 2 1]
 [3 4 5 2]
 [6 7 8 3]]


In [ ]:
# 9.Matrix Multiplication in NumPy
print('\033[1m' + "9.Matrix Multiplication in NumPy\n" + '\033[0m')

matrix1 = np.matrix([[1, 2],
                     [3, 4]])
matrix2 = np.matrix([[1, 2],
                     [1, 2]])
print("Matrix Multiplication: \n", np.matmul(matrix1, matrix2))

9.Matrix Multiplication in NumPy

Matrix Multiplication: 
 [[ 3  6]
 [ 7 14]]


In [ ]:
# 10.Get the eigen values of a matrix
print('\033[1m' + "10.Get the eigen values of a matrix\n" + '\033[0m')
matrix = np.matrix([[1, 2],
                    [3, 4]])
eigenValues, _ = np.linalg.eig(matrix)
print("Eigen Values: ", eigenValues)

10.Get the eigen values of a matrix

Eigen Values:  [-0.37228132  5.37228132]


In [ ]:
# 11.How to Calculate the determinant of a matrix using NumPy?
print('\033[1m' + "11.How to Calculate the determinant of a matrix using NumPy?\n" + '\033[0m')
matrix = np.matrix([[1, 2],
                    [3, 4]])

det = np.linalg.det(matrix)

print("Determinante: ", det)

11.How to Calculate the determinant of a matrix using NumPy?

Determinante:  -2.0000000000000004


In [ ]:
# 12.How to inverse a matrix using NumPy
print('\033[1m' + "12.How to inverse a matrix using NumPy\n" + '\033[0m')

matrix = np.matrix([[1, 2],
                    [3, 4]])

inverseMatrix = np.linalg.inv(matrix)

print("Inverse Matrix: \n", inverseMatrix)

12.How to inverse a matrix using NumPy

Inverse Matrix: 
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
# 13.How to count the frequency of unique values in NumPy array?
print('\033[1m' + "13.How to count the frequency of unique values in NumPy array?\n" + '\033[0m')

array = np.array([1, 2, 3, 4, 3, 4])
  
uniqueValues, frequency = np.unique(array, return_counts = True)

print("Unique Values: ", uniqueValues)

print("Frequency Values: ", frequency)

13.How to count the frequency of unique values in NumPy array?

Unique Values:  [1 2 3 4]
Frequency Values:  [1 1 2 2]


In [ ]:
# 14.Multiply matrices of complex numbers using NumPy in Python
print('\033[1m' + "14.Multiply matrices of complex numbers using NumPy in Python\n" + '\033[0m')

matrix1 = np.array([1+2j,3+4j])
matrix2 = np.array([5+6j,7+8j])

print("Matrix 1: \n", matrix1)
print("Matrix 2: \n", matrix2)

Multiplication = np.vdot(matrix1, matrix2)
print("Multiplication: \n", Multiplication)

14.Multiply matrices of complex numbers using NumPy in Python

Matrix 1: 
 [1.+2.j 3.+4.j]
Matrix 2: 
 [5.+6.j 7.+8.j]
Multiplication: 
 (70-8j)


In [ ]:
# 15.Compute the outer product of two given vectors using NumPy in Python
print('\033[1m' + "15.Compute the outer product of two given vectors using NumPy in Python\n" + '\033[0m')

array1 = np.array([1, 2])
array2 = np.array([3, 4])

print("Outer product: \n", np.outer(array1, array2))

15.Compute the outer product of two given vectors using NumPy in Python

Outer product: 
 [[3 4]
 [6 8]]


In [ ]:
# 16.Calculate inner, outer, and cross products of matrices and vectors using NumPy
print('\033[1m' + "16.Calculate inner, outer, and cross products of matrices and vectors using NumPy\n" + '\033[0m')

array1 = np.array([1, 2])
array2 = np.array([3, 4])

print("Vector: \n")

print("Outer product: \n", np.outer(array1, array2))

print("Inner product: \n", np.outer(array1, array2))

print("Cross product: \n", np.cross(array1, array2))

matrix1 = np.matrix([[1, 2, 3], 
                    [4, 5, 6]])
matrix2 = np.matrix([[7, 8, 9], 
                    [10, 11, 12]])

print("\nMatrices: \n")

print("Outer product: \n", np.outer(matrix1, matrix2))

print("Inner product: \n", np.outer(matrix1, matrix2))

print("Cross product: \n", np.cross(matrix1, matrix2))

16.Calculate inner, outer, and cross products of matrices and vectors using NumPy

Vector: 

Outer product: 
 [[3 4]
 [6 8]]
Inner product: 
 [[3 4]
 [6 8]]
Cross product: 
 -2

Matrices: 

Outer product: 
 [[ 7  8  9 10 11 12]
 [14 16 18 20 22 24]
 [21 24 27 30 33 36]
 [28 32 36 40 44 48]
 [35 40 45 50 55 60]
 [42 48 54 60 66 72]]
Inner product: 
 [[ 7  8  9 10 11 12]
 [14 16 18 20 22 24]
 [21 24 27 30 33 36]
 [28 32 36 40 44 48]
 [35 40 45 50 55 60]
 [42 48 54 60 66 72]]
Cross product: 
 [[-6 12 -6]
 [-6 12 -6]]


In [ ]:
# 17.Compute the covariance matrix of two given NumPy arrays
print('\033[1m' + "17.Compute the covariance matrix of two given NumPy arrays\n" + '\033[0m')

array1 = np.arange(6)
array2 = np.flip(array1)

print(np.cov(array1, array2))

17.Compute the covariance matrix of two given NumPy arrays

[[ 3.5 -3.5]
 [-3.5  3.5]]


In [ ]:
# 18.Convert covariance matrix to correlation matrix using Python
print('\033[1m' + "18.Convert covariance matrix to correlation matrix using Python\n" + '\033[0m')

rng = np.random.default_rng(seed=42)
array = rng.random((3, 3))

np.corrcoef(array, rowvar=False)

18.Convert covariance matrix to correlation matrix using Python



array([[ 1.        ,  0.77598074, -0.47458546],
       [ 0.77598074,  1.        , -0.92346708],
       [-0.47458546, -0.92346708,  1.        ]])

In [ ]:
# 19.Compute the Kronecker product of two mulitdimension NumPy arrays
print('\033[1m' + "19.Compute the Kronecker product of two mulitdimension NumPy arrays\n" + '\033[0m')
# Creating arrays
array1 = np.array([[1, 2], 
                   [3, 4]])
 
array2 = np.array([[5, 6], 
                   [7, 8]])

kroneckerProduct = np.kron(array1, array2)
print("Kronecker Product: \n", kroneckerProduct)

19.Compute the Kronecker product of two mulitdimension NumPy arrays

Kronecker Product: 
 [[ 5  6 10 12]
 [ 7  8 14 16]
 [15 18 20 24]
 [21 24 28 32]]


In [ ]:
# 20.Convert the matrix into a list
print('\033[1m' + "20.Convert the matrix into a list\n" + '\033[0m')

matrix = np.matrix([[1, 2], 
                   [3, 4]])

print("Lista: \n", matrix.tolist())

20.Convert the matrix into a list

Lista: 
 [[1, 2], [3, 4]]


#**Questions on NumPy Indexing**

In [ ]:
# 1.Replace NumPy array elements that doesn’t satisfy the given condition
print('\033[1m' + "1.Replace NumPy array elements that doesn’t satisfy the given condition\n" + '\033[0m')

array = np.array([[1, 2],
                  [3, 4]])
array[array >= 3] = 0
print("Replaced Array: \n", array)

1.Replace NumPy array elements that doesn’t satisfy the given condition

Replaced Array: 
 [[1 2]
 [0 0]]


In [ ]:
# 2.Return the indices of elements where the given condition is satisfied
print('\033[1m' + "2.Return the indices of elements where the given condition is satisfied\n" + '\033[0m')

array = np.array([[1, 2],
                  [3, 4]])

indices = np.where(array >= 3)

print("Indices: \n", indices)

2.Return the indices of elements where the given condition is satisfied

Indices: 
 (array([1, 1]), array([0, 1]))


In [ ]:
# 3.Replace NaN values with average of columns
print('\033[1m' + "3.Replace NaN values with average of columns\n" + '\033[0m')

array = np.array([[1, np.nan],
                  [3, 4]])

# Pega a média da coluna
colMean = np.nanmean(array, axis=0)

# Pega os índices com NaN
indices = np.where(np.isnan(array))

# Insere a média da coluna onde tem NaN
array[indices] = np.take(colMean, indices[1])

print("Replaced Array: \n", array)

3.Replace NaN values with average of columns

Replaced Array: 
 [[1. 4.]
 [3. 4.]]


In [ ]:
# 4.Replace negative value with zero in numpy array
print('\033[1m' + "4.Replace negative value with zero in numpy array\n" + '\033[0m')

array = np.array([[1, -2],
                  [-3, 4]])

array[array < 0] = 0

print("Replaced Array: \n", array)

4.Replace negative value with zero in numpy array

Replaced Array: 
 [[1 0]
 [0 4]]


In [ ]:
# 5.How to get values of an NumPy array at certain index positions?
print('\033[1m' + "5.How to get values of an NumPy array at certain index positions?\n" + '\033[0m')

array = np.array([1, 2, 3, 4, 5, 6, 7])

print("Values in certain index positions: \n", array[[0, 4, 6]])

5.How to get values of an NumPy array at certain index positions?

Values in certain index positions: 
 [1 5 7]


In [ ]:
# 6.Find indices of elements equal to zero in a NumPy array
print('\033[1m' + "6.Find indices of elements equal to zero in a NumPy array\n" + '\033[0m')

array = np.array([1, 2, 0, 4, 5, 0, 7])

print("Indices of elements equal to zero: \n", np.where(array == 0))

6.Find indices of elements equal to zero in a NumPy array

Indices of elements equal to zero: 
 (array([2, 5]),)


In [ ]:
# 7.How to Remove columns in Numpy array that contains non-numeric values?
print('\033[1m' + "7.How to Remove columns in Numpy array that contains non-numeric values?\n" + '\033[0m')
array = np.array([[1, np.nan],
                  [3, 4]])

print("", array[:, ~np.isnan(array).any(axis=0)])

7.How to Remove columns in Numpy array that contains non-numeric values?

[[1.]
 [3.]]


In [ ]:
# 8.How to access different rows of a multidimensional NumPy array?
print('\033[1m' + "8.How to access different rows of a multidimensional NumPy array?\n" + '\033[0m')

array = np.array([[1, np.nan],
                  [3, 4],
                  [5, 6]])
print("Different rows: \n", array[[1,2]])

8.How to access different rows of a multidimensional NumPy array?

Different rows: 
 [[3. 4.]
 [5. 6.]]


In [ ]:
# 9.Get row numbers of NumPy array having element larger than X
print('\033[1m' + "9.Get row numbers of NumPy array having element larger than X\n" + '\033[0m')

array = np.array([[1, 2],
                  [3, 4],
                  [5, 6]])

X = 4

output  = np.where(np.any(array > X, axis = 1))

print("Result:\n", output)

9.Get row numbers of NumPy array having element larger than X

Result:
 (array([2]),)


In [ ]:
# 10.Get filled the diagonals of NumPy array
print('\033[1m' + "10.Get filled the diagonals of NumPy array\n" + '\033[0m')

array = np.arange(3 * 3).reshape(3, 3)
np.fill_diagonal(array, -1)
print(array)

10.Get filled the diagonals of NumPy array

[[-1  1  2]
 [ 3 -1  5]
 [ 6  7 -1]]


In [ ]:
# 11.Check elements present in the NumPy array
print('\033[1m' + "11.Check elements present in the NumPy array\n" + '\033[0m')

array = np.arange(1, 7).reshape(2, 3)
value = 6

if(value in array):
    print(f"O valor \"{value}\" está no array: \n{array}")
else:
    print(f"O valor \"{value}\" não está no array: \n{array}")

11.Check elements present in the NumPy array

O valor "6" está no array: 
[[1 2 3]
 [4 5 6]]


In [ ]:
# 12.Combined array index by index
print('\033[1m' + "12.Combined array index by index\n" + '\033[0m')

arrayTwoDim = np.array([[1, 8, 2], 
                        [2, 8, 8]])

arrayOneDim = np.array([1, 2, 3])
print("Array com uma dimensão: \n", arrayOneDim)
print("Array com duas dimensão: \n", arrayTwoDim)
print()
for i, j in np.nditer([arrayOneDim, arrayTwoDim]):
    print(i, "|", j)

12.Combined array index by index

Array com uma dimensão: 
 [1 2 3]
Array com duas dimensão: 
 [[1 8 2]
 [2 8 8]]

1 | 1
2 | 8
3 | 2
1 | 2
2 | 8
3 | 8


#**Questions on NumPy Linear Algebra**

In [ ]:
# 1.Find a matrix or vector norm using NumPy


In [ ]:
# 2.Calculate the QR decomposition of a given matrix using NumPy


In [ ]:
# 3.Compute the condition number of a given matrix using NumPy


In [ ]:
# 4.Compute the eigenvalues and right eigenvectors of a given square array using NumPy?


In [ ]:
# 5.Calculate the Euclidean distance using NumPy

#**Questions on NumPy Random**

In [ ]:
# 1.Create a Numpy array with random values


In [ ]:
# 2.How to choose elements from the list with different probability using NumPy?


In [ ]:
# 3.How to get weighted random choice in Python?


In [ ]:
# 4.Generate Random Numbers From The Uniform Distribution using NumPy


In [ ]:
# 5.Get Random Elements form geometric distribution


In [ ]:
# 6.Get Random elements from Laplace distribution


In [ ]:
# 7.Return a Matrix of random values from a uniform distribution


In [ ]:
# 8.Return a Matrix of random values from a Gaussian distribution

#**Questions on NumPy Sorting and Searching**

In [ ]:
# 1.How to get the indices of the sorted array using NumPy in Python?


In [ ]:
# 2.Finding the k smallest values of a NumPy array


In [ ]:
# 3.How to get the n-largest values of an array using NumPy?


In [ ]:
# 4.Sort the values in a matrix


In [ ]:
# 5.Filter out integers from float numpy array


In [ ]:
# 6.Find the indices into a sorted array

#**Questions on NumPy Mathematics**

In [ ]:
# 1.How to get element-wise true division of an array using Numpy?


In [ ]:
# 2.How to calculate the element-wise absolute value of NumPy array?


In [ ]:
# 3.Compute the negative of the NumPy array


In [ ]:
# 4.Multiply 2d numpy array corresponding to 1d array


In [ ]:
# 5.Computes the inner product of two arrays


In [ ]:
# 6.Compute the nth percentile of the NumPy array


In [ ]:
# 7.Calculate the n-th order discrete difference along the given axis


In [ ]:
# 8.Calculate the sum of all columns in a 2D NumPy array


In [ ]:
# 9.Calculate average values of two given NumPy arrays


In [ ]:
# 10.How to compute numerical negative value for all elements in a given NumPy array?


In [ ]:
# 11.How to get the floor, ceiling and truncated values of the elements of a numpy array?


In [ ]:
# 12.How to round elements of the NumPy array to the nearest integer?


In [ ]:
# 13.Find the round off the values of the given matrix


In [ ]:
# 14.Determine the positive square-root of an array


In [ ]:
# 15.Evaluate Einstein’s summation convention of two multidimensional NumPy arrays

#**Questions on NumPy Statistics**

In [ ]:
# 1.Compute the median of the flattened NumPy array


In [ ]:
# 2.Find Mean of a List of Numpy Array


In [ ]:
# 3.Calculate the mean of array ignoring the NaN value


In [ ]:
# 4.Get the mean value from given matrix


In [ ]:
# 5.Compute the variance of the NumPy array


In [ ]:
# 6.Compute the standard deviation of the NumPy array


In [ ]:
# 7.Compute pearson product-moment correlation coefficients of two given NumPy arrays


In [ ]:
# 8.Calculate the mean across dimension in a 2D NumPy array


In [ ]:
# 9.Calculate the average, variance and standard deviation in Python using NumPy


In [ ]:
# 10.Describe a NumPy Array in Python

#**Questions on Polynomial**

In [ ]:
# 1.Define a polynomial function


In [ ]:
# 2.How to add one polynomial to another using NumPy in Python?


In [ ]:
# 3.How to subtract one polynomial to another using NumPy in Python?


In [ ]:
# 4.How to multiply a polynomial to another using NumPy in Python?


In [ ]:
# 5.How to divide a polynomial to another using NumPy in Python?


In [ ]:
# 6.Find the roots of the polynomials using NumPy


In [ ]:
# 7.Evaluate a 2-D polynomial series on the Cartesian product


In [ ]:
# 8.Evaluate a 3-D polynomial series on the Cartesian product

#**Questions on NumPy Strings**

In [ ]:
# 1.Repeat all the elements of a NumPy array of strings


In [ ]:
# 2.How to split the element of a given NumPy array with spaces?


In [ ]:
# 3.How to insert a space between characters of all the elements of a given NumPy array?


In [ ]:
# 4.Find the length of each string element in the Numpy array


In [ ]:
# 5.Swap the case of an array of string


In [ ]:
# 6.Change the case to uppercase of elements of an array


In [ ]:
# 7.Change the case to lowercase of elements of an array


In [ ]:
# 8.Join String by a seperator


In [ ]:
# 9.Check if two same shaped string arrayss one by one


In [ ]:
# 10.Count the number of substrings in an array


In [ ]:
# 11.Find the lowest index of the substring in an array


In [ ]:
# 12.Get the boolean array when values end with a particular character

In [ ]:
# 13.More Questions on NumPy

In [ ]:
# 14.Different ways to convert a Python dictionary to a NumPy array


In [ ]:
# 15.How to convert a list and tuple into NumPy arrays?


In [ ]:
# 16.Ways to convert array of strings to array of floats


In [ ]:
# 17.Convert a NumPy array into a csv file


In [ ]:
# 18.How to Convert an image to NumPy array and save it to CSV file using Python?


In [ ]:
# 19.How to save a NumPy array to a text file?


In [ ]:
# 20.Load data from a text file


In [ ]:
# 21.Plot line graph from NumPy array


In [ ]:
# 22.Create Histogram using NumPy